services:
  app:
    build:
      dockerfile: ./docker-build/app/Dockerfile
      context: ./
    ports:
      - "127.0.0.1:8013:8000"
    volumes:
      - ./src:/src
      - ./src/.env:/src/.env
      - ./src/certs:/src/certs
      - ./src/alembic:/src/alembic
      - ./src/alembic.ini:/src/alembic.ini
      - /etc/localtime:/etc/localtime:ro
      - ./src/storage:/src/storage
#    command:
#      - python
#      - run_main.py
    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: ./src
    #       target: /src
    #     - action: rebuild
    #       path: ./poetry.lock
    networks:
      - admin_joo
      - infra_shared_network


  worker:
    build:
      context: ./
      dockerfile: ./docker-build/app/Dockerfile
    command: arq app.core.worker.settings.WorkerSettings
    env_file:
      - ./src/.env
    volumes:
      - ./src/.env:/src/.env
      - ./src/app:/src/app
      - /etc/localtime:/etc/localtime:ro
      - ./src/storage:/src/storage
    networks:
      - admin_joo
      - infra_shared_network

  # init_scripts:
  #   build:
  #     context: ./
  #     dockerfile: ./docker-build/app/Dockerfile
  #   env_file:
  #     - ./src/.env

  #   volumes:
  #     - ./src:/src
  #     - ./src/.env:/src/.env
  #     - ./src/certs:/src/certs:ro

  #   command: >
  #     sh -c "
  #       python -m scripts.create_first_superuser
  #       python -m scripts.create_first_tier
  #       python -m scripts.create_roles
  #       python -m scripts.create_departments
  #       python -m scripts.create_persons
  #     "
  #   networks:
  #     - admin_joo
  #     - infra_shared_network

networks:
  admin_joo:
    driver: bridge
  infra_shared_network:
    external: true
    