"""update feedback

Revision ID: 3ad8b54357c4
Revises: ef3454001aa3
Create Date: 2025-09-17 19:37:26.680900

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ad8b54357c4"
down_revision: Union[str, None] = "ef3454001aa3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("branches", sa.Column("rating_1_count", sa.Integer(), nullable=False))
    op.add_column("branches", sa.Column("rating_2_count", sa.Integer(), nullable=False))
    op.add_column("branches", sa.Column("rating_3_count", sa.Integer(), nullable=False))
    op.add_column("branches", sa.Column("rating_4_count", sa.Integer(), nullable=False))
    op.add_column("branches", sa.Column("rating_5_count", sa.Integer(), nullable=False))
    op.drop_column("branches", "rating")
    op.drop_column("branches", "voice_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "branches",
        sa.Column("voice_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "branches",
        sa.Column(
            "rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("branches", "rating_5_count")
    op.drop_column("branches", "rating_4_count")
    op.drop_column("branches", "rating_3_count")
    op.drop_column("branches", "rating_2_count")
    op.drop_column("branches", "rating_1_count")
    # ### end Alembic commands ###
