"""empty message

Revision ID: 132680b5c483
Revises:
Create Date: 2025-08-04 20:25:25.849256

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "132680b5c483"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
