"""empty message

Revision ID: ceee97e4a45d
Revises: 63fe70618caf
Create Date: 2025-08-05 21:53:31.669355

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ceee97e4a45d"
down_revision: Union[str, None] = "63fe70618caf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_persons_role_id_roles", "persons", type_="foreignkey")
    op.drop_column("persons", "role_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persons",
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_persons_role_id_roles", "persons", "roles", ["role_id"], ["id"]
    )
    # ### end Alembic commands ###
